### ISSUE TITLE
Can't install pandas dependency

### ISSUE THREAD

**Issue by Goufalite** [wizmer/banquepostale-pdf-to-csv#1]
Hello, I'm trying to run the script on a rapsberry pi 1B+but it needs the pandas dependency to continue.

Is there a specific way to install this dependency on this device ? According to Google it is quite complicated even on a RP3... 
Is there an OS/Python version requirement for your script ?

Thank you in advance !

Sidenote : Glad to see I'm not the only one to struggle with locked PDFs... you can export transactions directly to csv/ofx by clicking a bank account > "Télécharger le détail" > "Modifier" > choose format and time restriction. You won't have the PDF summary but it is better than nothing...

**Comment by wizmer** [comment]
Hello, 

I've been running the script under my Ubuntu 16.04 but that's all I can tell about the requirements.
I guess you did but have you tried the solution https://raspberrypi.stackexchange.com/a/17074 suggested here ? 

Otherwise, you could replace the Pandas dataframe by a numpy array if you think numpy would be easier to install. I can help you with that if needed.

About your sidenote: using your suggestion I can only go a few month back in time so I had to go through the PDF way to retrieve older data.

**Comment by Goufalite** [comment]
Here's what I've done
- installed the pandas through apt-get
> Traceback (most recent call last):
  File "csv.py", line 8, in <module>
    import pandas as pd
  File "/usr/lib/pymodules/python2.7/pandas/__init__.py", line 24, in <module>
    from pandas.core.api import *
  File "/usr/lib/pymodules/python2.7/pandas/core/api.py", line 6, in <module>
    from pandas.core.algorithms import factorize, match, unique, value_counts
  File "/usr/lib/pymodules/python2.7/pandas/core/algorithms.py", line 8, in <module>
    import pandas.core.common as com
  File "/usr/lib/pymodules/python2.7/pandas/core/common.py", line 872, in <module>
    class UnicodeReader:
  File "/usr/lib/pymodules/python2.7/pandas/core/common.py", line 881, in UnicodeReader
    def __init__(self, f, dialect=csv.excel, encoding="utf-8", **kwds):
AttributeError: 'module' object has no attribute 'excel'

I tried to install it through pip3 (pip-3.2) but it doesn't seem to fetch the pip repo url which is another hair-scratching problem... https://stackoverflow.com/questions/38869231/python-cant-find-the-file-pip-conf-in-linux

Therefore I'll take a look at numpy if I have some time

**Comment by oaubert** [comment]
Thanks for you code. I started to do some fixes to it, but ended up doing a whole rewrite of the program, changing the whole code logic, command line and output format. So I decided to create another project instead of submitting a pull request: https://github.com/oaubert/banquepostale-pdf-to-tsv
If fixes this bug since it does not rely on pandas anymore. It simply outputs text lines (with tab-separated values).
